### ISSUE TITLE
真机运行崩溃

### ISSUE THREAD

**Issue by Hell-And** [JustinRoom/WheelViewDemo#1]
12-10 09:27:31.490 2362-2362/jsc.exam.com.wheelview E/AndroidRuntime: FATAL EXCEPTION: main
    Process: jsc.exam.com.wheelview, PID: 2362
    java.lang.NoSuchMethodError: jsc.exam.com.wheelview.widgets.DotView.setClipToOutline
        at jsc.exam.com.wheelview.widgets.DotView.initAttr(DotView.java:61)
        at jsc.exam.com.wheelview.widgets.DotView.<init>(DotView.java:46)
        at jsc.exam.com.wheelview.widgets.JSCItemLayout.initAttr(JSCItemLayout.java:88)
        at jsc.exam.com.wheelview.widgets.JSCItemLayout.<init>(JSCItemLayout.java:39)
        at jsc.exam.com.wheelview.adapter.ClassItemAdapter.createView(ClassItemAdapter.java:29)
        at jsc.exam.com.wheelview.adapter.ClassItemAdapter.onCreateViewHolder(ClassItemAdapter.java:50)
        at jsc.exam.com.wheelview.adapter.ClassItemAdapter.onCreateViewHolder(ClassItemAdapter.java:14)

**Comment by JustinRoom** [comment]
这是demo里的自定义view，我用了LOLLIPOP（21）api里的方法。我已经改了兼容性，你下载最新的源码试试。

**Comment by Hell-And** [comment]
> 这是demo里的自定义view，我用了LOLLIPOP（21）api里的方法。我已经改了兼容性，你下载最新的源码试试。

OK了
